//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        public int IdBoleta { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public Nullable<int> Pedido { get; set; }
        public Nullable<double> Descuento { get; set; }
    
        public virtual TipoPago TipoPago { get; set; }
        public virtual Pedido Pedido1 { get; set; }
    }
}
