//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquivalenciaMediciones
    {
        public int IdEquivalencia { get; set; }
        public int IdTipoMedicionInicial { get; set; }
        public int Equivalencia { get; set; }
        public int IdTipoMedicionEquivalente { get; set; }
    
        public virtual TipoMedicion TipoMedicion { get; set; }
        public virtual TipoMedicion TipoMedicion1 { get; set; }
    }
}
