//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraDisponible
    {
        public int IdExtraDisponible { get; set; }
        public int IdAlimento { get; set; }
        public int IdIngrediente { get; set; }
        public Nullable<int> CantidadMaxima { get; set; }
        public Nullable<int> Valor { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
    }
}
