//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.IngredienteFactura = new HashSet<IngredienteFactura>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<int> TotalNeto { get; set; }
        public Nullable<double> TotalIva { get; set; }
        public Nullable<int> IdDistribuidor { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Folio { get; set; }
    
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredienteFactura> IngredienteFactura { get; set; }
    }
}
