//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrderNowBDEntities : DbContext
    {
        public OrderNowBDEntities()
            : base("name=OrderNowBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<AlimentoPedido> AlimentoPedido { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Distribuidor> Distribuidor { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<ExtraPedido> ExtraPedido { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<IngredienteFactura> IngredienteFactura { get; set; }
        public virtual DbSet<IngredientesAlimento> IngredientesAlimento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<OfertaAlimento> OfertaAlimento { get; set; }
        public virtual DbSet<OfertaPedido> OfertaPedido { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoAlimento> TipoAlimento { get; set; }
        public virtual DbSet<TipoMedicion> TipoMedicion { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<TipoPedido> TipoPedido { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ClasificacionAlimento> ClasificacionAlimento { get; set; }
        public virtual DbSet<EquivalenciaMediciones> EquivalenciaMediciones { get; set; }
        public virtual DbSet<DetalleIngrediente> DetalleIngrediente { get; set; }
        public virtual DbSet<ExtraDisponible> ExtraDisponible { get; set; }
    
        public virtual ObjectResult<ExtraDisponible> P_obtener_extras_disponibles(Nullable<int> pin_codigo)
        {
            var pin_codigoParameter = pin_codigo.HasValue ?
                new ObjectParameter("Pin_codigo", pin_codigo) :
                new ObjectParameter("Pin_codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExtraDisponible>("P_obtener_extras_disponibles", pin_codigoParameter);
        }
    
        public virtual ObjectResult<ExtraDisponible> P_obtener_extras_disponibles(Nullable<int> pin_codigo, MergeOption mergeOption)
        {
            var pin_codigoParameter = pin_codigo.HasValue ?
                new ObjectParameter("Pin_codigo", pin_codigo) :
                new ObjectParameter("Pin_codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExtraDisponible>("P_obtener_extras_disponibles", mergeOption, pin_codigoParameter);
        }
    }
}
