//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderNowBDEntities : DbContext
    {
        public OrderNowBDEntities()
            : base("name=OrderNowBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<AlimentoPedido> AlimentoPedido { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Distribuidor> Distribuidor { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<ExtraPedido> ExtraPedido { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<IngredienteFactura> IngredienteFactura { get; set; }
        public virtual DbSet<IngredientesAlimento> IngredientesAlimento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<OfertaAlimento> OfertaAlimento { get; set; }
        public virtual DbSet<OfertaPedido> OfertaPedido { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoAlimento> TipoAlimento { get; set; }
        public virtual DbSet<TipoMedicion> TipoMedicion { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<TipoPedido> TipoPedido { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
