//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderNowDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.AlimentoPedido = new HashSet<AlimentoPedido>();
            this.Boleta = new HashSet<Boleta>();
            this.OfertaPedido = new HashSet<OfertaPedido>();
        }
    
        public int IdPedido { get; set; }
        public Nullable<int> IdEstadoPedido { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> Trabajador { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public string Direccion { get; set; }
        public string Observación { get; set; }
        public Nullable<int> IdTipoModalidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlimentoPedido> AlimentoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta> Boleta { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfertaPedido> OfertaPedido { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual Trabajador Trabajador1 { get; set; }
        public virtual TipoModalidad TipoModalidad { get; set; }
    }
}
